# Taken from the Invidious project
# more specifically from this PR: https://github.com/iv-org/invidious/pull/2264
name: Lens CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    name: "build - crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"

    continue-on-error: ${{ !matrix.stable }}

    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.0.0
          - 1.1.0
          - 1.1.1
        include:
          - crystal: nightly
            stable: false

    steps:
      - uses: actions/checkout@v2

      - name: Install Crystal
        uses: oprypin/install-crystal@v1.2.4
        with:
          crystal: ${{ matrix.crystal }}

      - name: Cache Shards
        uses: actions/cache@v2
        with:
          path: ./lib
          key: shards-${{ hashFiles('shard.lock') }}

      - name: Install Shards
        run: |
          if ! shards check; then
            shards install
          fi
      - name: Run tests
        run: crystal spec

      - name: Run lint
        run: |
          if ! crystal tool format --check; then
            crystal tool format
            git diff
            exit 1
          fi
      - name: Build
        run: crystal build --warnings all --error-on-warnings --error-trace src/lens.cr