name: Generate documentation

on:
  push:
    branches:
      - "master"
      - "docs"
  workflow_dispatch:

jobs:
  documentation:
    runs-on: "ubuntu-latest"
    name: "Generate documentation"


    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - name: "Deploy documentation"
        run: mkdocs gh-deploy --force

      - name: Checkout master to build API docs
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Crystal
        uses: oprypin/install-crystal@v1.2.4
        with:
          crystal: ${{ matrix.crystal }}

      - name: Cache Shards
        uses: actions/cache@v2
        with:
          path: ./lib
          key: shards-${{ hashFiles('shard.lock') }}

      - name: Install Shards
        run: |
          if ! shards check; then
            shards install
          fi
      - name: Run tests
        run: crystal spec --error-trace

      - name: Build API docs
        run: crystal docs --output=api
      - name: Deploy API docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: api
          target-folder: api
          clean: false