name: Generate documentation

on:
  push:
    branches:
      - "master"
      - "docs"

jobs:
  documentation:
    runs-on: "ubuntu-latest"
    name: "Generate documentation"


    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - name: "Deploy documentation"
        run: mkdocs gh-deploy --force

      - name: Checkout master to build API docs
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build API docs
        run: crystal docs --output=api
      - name: Deploy API docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: api